version: '3.8'

services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgdbRogier22
      POSTGRES_DB: transaction_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  icountant-api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
